version: '3.8' # Użyj odpowiedniej wersji compose

services:
  app:
    build: . # Zbuduj obraz używając Dockerfile w bieżącym katalogu
    container_name: node_app_dev # Opcjonalna nazwa kontenera
    ports:
      - "3000:3000" # Mapuj port 3000 hosta na port 3000 kontenera
    environment:
      - MONGODB_URI=mongodb://mongo:27017/usersdb
      - PORT=3000
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    depends_on:
      - mongo # Upewnij się, że serwis mongo uruchomi się przed app
    networks:
      - app-network # Użyj zdefiniowanej sieci

  mongo:
    image: mongo:6 # Użyj oficjalnego obrazu MongoDB (np. wersja 6)
    container_name: mongo_db_dev # Opcjonalna nazwa kontenera
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network # Użyj zdefiniowanej sieci

networks:
  app-network:
    driver: bridge # Domyślny sterownik sieciowy dla compose

volumes:
  mongo-data: # Wolumen do przechowywania danych MongoDB
